# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63e787f7f68ec4a80d0a119a99982dcfde7a554bb2cb65ee1b9ff51f6bd4ceeca6ac3f4fdfb7c26ebb972b569bbcbcb27982d74352b4c085f512ac02e0caad95

test:
  secret_key_base: 160117443dc32341fad84e0cbd1078b277250b0e94dcac9c7adecaec70700e8c666c43aa9ff52f77b7b699cb2000396ca85d10a26b146d142f22d194e9d971a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
